apiVersion: v1
name: istio
version: 1.1.11
appVersion: release-1.1-20190719-09-16
tillerVersion: ">=2.7.2-0"
description: Helm chart for all istio components
keywords:
  - istio
  - security
  - sidecarInjectorWebhook
  - mixer
  - pilot
  - galley
sources:
  - https://github.com/ArborMetrix/istio/tree/amx-1.1.11/install/kubernetes/helm
engine: gotpl
icon: https://istio.io/favicons/android-192x192.png
